// neon marquee fragment
@fragment fn fs(in: VsOut) -> @location(0) vec4<f32> {
  return vec4(in.uv, 0.6, 1.0);
}
// line 0  uv.y scroll
// line 1  uv.y scroll
// line 2  uv.y scroll
// line 3  uv.y scroll
// line 4  uv.y scroll
// line 5  uv.y scroll
// line 6  uv.y scroll
// line 7  uv.y scroll
// line 8  uv.y scroll
// line 9  uv.y scroll
// line 10  uv.y scroll
// line 11  uv.y scroll
// line 12  uv.y scroll
// line 13  uv.y scroll
// line 14  uv.y scroll
// line 15  uv.y scroll
// line 16  uv.y scroll
// line 17  uv.y scroll
// line 18  uv.y scroll
// line 19  uv.y scroll
// line 20  uv.y scroll
// line 21  uv.y scroll
// line 22  uv.y scroll
// line 23  uv.y scroll
// line 24  uv.y scroll
// line 25  uv.y scroll
// line 26  uv.y scroll
// line 27  uv.y scroll
// line 28  uv.y scroll
// line 29  uv.y scroll
// line 30  uv.y scroll
// line 31  uv.y scroll
// line 32  uv.y scroll
// line 33  uv.y scroll
// line 34  uv.y scroll
// line 35  uv.y scroll
// line 36  uv.y scroll
// line 37  uv.y scroll
// line 38  uv.y scroll
// line 39  uv.y scroll
// line 40  uv.y scroll
// line 41  uv.y scroll
// line 42  uv.y scroll
// line 43  uv.y scroll
// line 44  uv.y scroll
// line 45  uv.y scroll
// line 46  uv.y scroll
// line 47  uv.y scroll
// line 48  uv.y scroll
// line 49  uv.y scroll
// line 50  uv.y scroll
// line 51  uv.y scroll
// line 52  uv.y scroll
// line 53  uv.y scroll
// line 54  uv.y scroll
// line 55  uv.y scroll
// line 56  uv.y scroll
// line 57  uv.y scroll
// line 58  uv.y scroll
// line 59  uv.y scroll
// line 60  uv.y scroll
// line 61  uv.y scroll
// line 62  uv.y scroll
// line 63  uv.y scroll
// line 64  uv.y scroll
// line 65  uv.y scroll
// line 66  uv.y scroll
// line 67  uv.y scroll
// line 68  uv.y scroll
// line 69  uv.y scroll
// line 70  uv.y scroll
// line 71  uv.y scroll
// line 72  uv.y scroll
// line 73  uv.y scroll
// line 74  uv.y scroll
// line 75  uv.y scroll
// line 76  uv.y scroll
// line 77  uv.y scroll
// line 78  uv.y scroll
// line 79  uv.y scroll
// line 80  uv.y scroll
// line 81  uv.y scroll
// line 82  uv.y scroll
// line 83  uv.y scroll
// line 84  uv.y scroll
// line 85  uv.y scroll
// line 86  uv.y scroll
// line 87  uv.y scroll
// line 88  uv.y scroll
// line 89  uv.y scroll
// line 90  uv.y scroll
// line 91  uv.y scroll
// line 92  uv.y scroll
// line 93  uv.y scroll
// line 94  uv.y scroll
// line 95  uv.y scroll
// line 96  uv.y scroll
// line 97  uv.y scroll
// line 98  uv.y scroll
// line 99  uv.y scroll
// line 100  uv.y scroll
// line 101  uv.y scroll
// line 102  uv.y scroll
// line 103  uv.y scroll
// line 104  uv.y scroll
// line 105  uv.y scroll
// line 106  uv.y scroll
// line 107  uv.y scroll
// line 108  uv.y scroll
// line 109  uv.y scroll
// line 110  uv.y scroll
// line 111  uv.y scroll
// line 112  uv.y scroll
// line 113  uv.y scroll
// line 114  uv.y scroll
// line 115  uv.y scroll
// line 116  uv.y scroll
// line 117  uv.y scroll
// line 118  uv.y scroll
// line 119  uv.y scroll
// line 120  uv.y scroll
// line 121  uv.y scroll
// line 122  uv.y scroll
// line 123  uv.y scroll
// line 124  uv.y scroll
// line 125  uv.y scroll
// line 126  uv.y scroll
// line 127  uv.y scroll
// line 128  uv.y scroll
// line 129  uv.y scroll
// line 130  uv.y scroll
// line 131  uv.y scroll
// line 132  uv.y scroll
// line 133  uv.y scroll
// line 134  uv.y scroll
// line 135  uv.y scroll
// line 136  uv.y scroll
// line 137  uv.y scroll
// line 138  uv.y scroll
// line 139  uv.y scroll
// line 140  uv.y scroll
// line 141  uv.y scroll
// line 142  uv.y scroll
// line 143  uv.y scroll
// line 144  uv.y scroll
// line 145  uv.y scroll
// line 146  uv.y scroll
// line 147  uv.y scroll
// line 148  uv.y scroll
// line 149  uv.y scroll
// line 150  uv.y scroll
// line 151  uv.y scroll
// line 152  uv.y scroll
// line 153  uv.y scroll
// line 154  uv.y scroll
// line 155  uv.y scroll
// line 156  uv.y scroll
// line 157  uv.y scroll
// line 158  uv.y scroll
// line 159  uv.y scroll
// line 160  uv.y scroll
// line 161  uv.y scroll
// line 162  uv.y scroll
// line 163  uv.y scroll
// line 164  uv.y scroll
// line 165  uv.y scroll
// line 166  uv.y scroll
// line 167  uv.y scroll
// line 168  uv.y scroll
// line 169  uv.y scroll
// line 170  uv.y scroll
// line 171  uv.y scroll
// line 172  uv.y scroll
// line 173  uv.y scroll
// line 174  uv.y scroll
// line 175  uv.y scroll
// line 176  uv.y scroll
// line 177  uv.y scroll
// line 178  uv.y scroll
// line 179  uv.y scroll